import { Language } from './types';

const commonKeys = {
  title: 'CropGPT',
  dashboard: 'Dashboard',
  scanner: 'Scanner',
  chatbot: 'Chatbot',
  weather: 'Weather',
  marketPrices: 'Market Prices',
  yieldProduction: 'Yield Production',
  fetchWeather: 'Fetching Your Weather...',
  weatherError: 'Could not fetch weather. Please allow location access.',
  selectState: 'Select State',
  selectCity: 'Select City',
  selectCrop: 'Select Crop',
  fetch: 'Fetch',
  startScan: 'Start Camera',
  capture: 'Capture & Analyze',
  stopScan: 'Stop Camera',
  scanResult: 'Scan Result',
  askMe: 'Ask me about farming...',
  send: 'Send',
  lightMode: 'Light Mode',
  darkMode: 'Dark Mode',
  uploadImage: 'Upload Image',
  search: 'Search',
  waterNeeds: 'Crop Water Needs',
  searchLocationPlaceholder: 'Enter a city name...',
  analyzing: 'Analyzing...',
  uploadPrompt: 'Upload a clear photo of the crop',
  cameraOff: 'Camera is off',
  governmentSchemes: 'Government Schemes',
  retake: 'Retake',
  uploadAnother: 'Upload Another',
  fertilizers: 'Fertilizers',
  pesticides: 'Pesticides',
  recommendations: 'Recommendations',
  farmingCalendar: 'Farming Calendar',
  generateSchedule: 'Generate Schedule',
  generating: 'Generating...',
};

export const translations: Record<Language, Record<string, string>> = {
  en: commonKeys,
  hi: {
    ...commonKeys,
    title: 'क्रॉपजीपीटी',
    dashboard: 'डैशबोर्ड',
    scanner: 'स्कैनर',
    chatbot: 'चैटबॉट',
    weather: 'मौसम',
    marketPrices: 'बाजार मूल्य',
    yieldProduction: 'उपज उत्पादन',
    fetchWeather: 'आपका मौसम प्राप्त हो रहा है...',
    weatherError: 'मौसम प्राप्त नहीं हो सका। कृपया स्थान पहुंच की अनुमति दें।',
    selectState: 'राज्य चुनें',
    selectCity: 'शहर चुनें',
    selectCrop: 'फसल चुनें',
    fetch: 'प्राप्त करें',
    startScan: 'कैमरा शुरू करें',
    capture: 'कैप्चर और विश्लेषण करें',
    stopScan: 'कैमरा बंद करें',
    scanResult: 'स्कैन परिणाम',
    askMe: 'खेती के बारे में पूछें...',
    send: 'भेजें',
    lightMode: 'लाइट मोड',
    darkMode: 'डार्क मोड',
    uploadImage: 'छवि अपलोड करें',
    search: 'खोजें',
    waterNeeds: 'फसल की पानी की जरूरत',
    searchLocationPlaceholder: 'शहर का नाम दर्ज करें...',
    analyzing: 'विश्लेषण हो रहा है...',
    uploadPrompt: 'फसल की एक स्पष्ट तस्वीर अपलोड करें',
    cameraOff: 'कैमरा बंद है',
    governmentSchemes: 'सरकारी योजनाएं',
    retake: 'फिर से लें',
    uploadAnother: 'दूसरा अपलोड करें',
    fertilizers: 'उर्वरक',
    pesticides: 'कीटनाशक',
    recommendations: 'सिफारिशें',
    farmingCalendar: 'खेती कैलेंडर',
    generateSchedule: 'शेड्यूल बनाएं',
    generating: 'बनाया जा रहा है...',
  },
  ta: {
    ...commonKeys,
    title: 'பயிர்ஜிபிடி',
    dashboard: 'டாஷ்போர்டு',
    scanner: 'ஸ்கேனர்',
    chatbot: 'சாட்பாட்',
    weather: 'வானிலை',
    marketPrices: 'சந்தை விலைகள்',
    yieldProduction: 'விளைச்சல் உற்பத்தி',
    fetchWeather: 'உங்கள் வானிலை பெறப்படுகிறது...',
    weatherError: 'வானிலை பெற முடியவில்லை. இருப்பிட அணுகலை அனுமதிக்கவும்.',
    selectState: 'மாநிலத்தைத் தேர்ந்தெடுக்கவும்',
    selectCity: 'நகரத்தைத் தேர்ந்தெடுக்கவும்',
    selectCrop: 'பயிரைத் தேர்ந்தெடுக்கவும்',
    fetch: 'பெறு',
    startScan: 'கேமராவைத் தொடங்கு',
    capture: 'படம் எடுத்து பகுப்பாய்வு செய்',
    stopScan: 'கேமராவை நிறுத்து',
    scanResult: 'ஸ்கேன் முடிவு',
    askMe: 'விவசாயம் பற்றி கேளுங்கள்...',
    send: 'அனுப்பு',
    lightMode: 'ஒளி பயன்முறை',
    darkMode: 'இருண்ட பயன்முறை',
    uploadImage: 'படத்தை பதிவேற்று',
    search: 'தேடு',
    waterNeeds: 'பயிர் நீர் தேவைகள்',
    searchLocationPlaceholder: 'நகரத்தின் பெயரை உள்ளிடவும்...',
    analyzing: 'பகுப்பாய்வு செய்யப்படுகிறது...',
    uploadPrompt: 'பயிரின் தெளிவான புகைப்படத்தைப் பதிவேற்றவும்',
    cameraOff: 'கேமரா முடக்கப்பட்டுள்ளது',
    governmentSchemes: 'அரசு திட்டங்கள்',
    retake: 'மீண்டும் எடுக்கவும்',
    uploadAnother: 'மற்றொன்றை பதிவேற்று',
    fertilizers: 'உரங்கள்',
    pesticides: 'பூச்சிக்கொல்லிகள்',
    recommendations: 'பரிந்துரைகள்',
    farmingCalendar: 'விவசாய நாட்காட்டி',
    generateSchedule: 'அட்டவணையை உருவாக்கு',
    generating: 'உருவாக்கப்படுகிறது...',
  },
  pa: {
    ...commonKeys,
    title: 'ਫਸਲਜੀਪੀਟੀ',
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    scanner: 'ਸਕੈਨਰ',
    chatbot: 'ਚੈਟਬੋਟ',
    weather: 'ਮੌਸਮ',
    marketPrices: 'ਬਾਜ਼ਾਰ ਦੀਆਂ ਕੀਮਤਾਂ',
    yieldProduction: 'ਉਪਜ ਉਤਪਾਦਨ',
    fetchWeather: 'ਤੁਹਾਡਾ ਮੌਸਮ ਪ੍ਰਾਪਤ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...',
    weatherError: 'ਮੌਸਮ ਪ੍ਰਾਪਤ ਨਹੀਂ ਕੀਤਾ ਜਾ ਸਕਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਸਥਾਨ ਦੀ ਪਹੁੰਚ ਦੀ ਆਗਿਆ ਦਿਓ।',
    selectState: 'ਰਾਜ ਚੁਣੋ',
    selectCity: 'ਸ਼ਹਿਰ ਚੁਣੋ',
    selectCrop: 'ਫਸਲ ਚੁਣੋ',
    fetch: 'ਪ੍ਰਾਪਤ ਕਰੋ',
    startScan: 'ਕੈਮਰਾ ਸ਼ੁਰੂ ਕਰੋ',
    capture: 'ਕੈਪਚਰ ਅਤੇ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ',
    stopScan: 'ਕੈਮਰਾ ਬੰਦ ਕਰੋ',
    scanResult: 'ਸਕੈਨ ਨਤੀਜਾ',
    askMe: 'ਖੇਤੀਬਾੜੀ ਬਾਰੇ ਪੁੱਛੋ...',
    send: 'ਭੇਜੋ',
    lightMode: 'ਲਾਈਟ ਮੋਡ',
    darkMode: 'ਡਾਰਕ ਮੋਡ',
    uploadImage: 'ਚਿੱਤਰ ਅੱਪਲੋਡ ਕਰੋ',
    search: 'ਖੋਜ',
    waterNeeds: 'ਫਸਲ ਦੀਆਂ ਪਾਣੀ ਦੀਆਂ ਲੋੜਾਂ',
    searchLocationPlaceholder: 'ਇੱਕ ਸ਼ਹਿਰ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ...',
    analyzing: 'ਵਿਸ਼ਲੇਸ਼ਣ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...',
    uploadPrompt: 'ਫਸਲ ਦੀ ਇੱਕ ਸਾਫ਼ ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ',
    cameraOff: 'ਕੈਮਰਾ ਬੰਦ ਹੈ',
    governmentSchemes: 'ਸਰਕਾਰੀ ਸਕੀਮਾਂ',
    retake: 'ਦੁਬਾਰਾ ਲਓ',
    uploadAnother: 'ਹੋਰ ਅੱਪਲੋਡ ਕਰੋ',
    fertilizers: 'ਖਾਦਾਂ',
    pesticides: 'ਕੀਟਨਾਸ਼ਕ',
    recommendations: 'ਸਿਫਾਰਸ਼ਾਂ',
    farmingCalendar: 'ਖੇਤੀ ਕੈਲੰਡਰ',
    generateSchedule: 'ਸਮਾਂ-ਸਾਰਣੀ ਬਣਾਓ',
    generating: 'ਬਣਾਇਆ ਜਾ ਰਿਹਾ ਹੈ...',
  },
  bn: {
    ...commonKeys,
    title: 'ক্রপজিপিটি',
    dashboard: 'ড্যাশবোর্ড',
    scanner: 'স্ক্যানার',
    chatbot: 'চ্যাটবট',
    weather: 'আবহাওয়া',
    marketPrices: 'বাজার দর',
    yieldProduction: 'ফলন উৎপাদন',
    fetchWeather: 'আপনার আবহাওয়া আনা হচ্ছে...',
    weatherError: 'আবহাওয়া আনা যায়নি। অনুগ্রহ করে অবস্থান অ্যাক্সেসের অনুমতি দিন।',
    selectState: 'রাজ্য নির্বাচন করুন',
    selectCity: 'শহর নির্বাচন করুন',
    selectCrop: 'ফসল নির্বাচন করুন',
    fetch: 'আনুন',
    startScan: 'ক্যামেরা চালু করুন',
    capture: 'ক্যাপচার ও বিশ্লেষণ করুন',
    stopScan: 'ক্যামেরা বন্ধ করুন',
    scanResult: 'স্ক্যানের ফলাফল',
    askMe: 'কৃষি সম্পর্কে জিজ্ঞাসা করুন...',
    send: 'পাঠান',
    lightMode: 'লাইট মোড',
    darkMode: 'ডার্ক মোড',
    uploadImage: 'ছবি আপলোড করুন',
    search: 'অনুসন্ধান',
    waterNeeds: 'ফসলের জলের প্রয়োজন',
    searchLocationPlaceholder: 'একটি শহরের নাম লিখুন...',
    analyzing: 'বিশ্লেষণ করা হচ্ছে...',
    uploadPrompt: 'ফসলের একটি পরিষ্কার ছবি আপলোড করুন',
    cameraOff: 'ক্যামেরা বন্ধ',
    governmentSchemes: 'সরকারি প্রকল্প',
    retake: 'আবার তুলুন',
    uploadAnother: 'অন্যটি আপলোড করুন',
    fertilizers: 'সার',
    pesticides: 'কীটনাশক',
    recommendations: 'সুপারিশ',
    farmingCalendar: 'কৃষি ক্যালেন্ডার',
    generateSchedule: 'সময়সূচী তৈরি করুন',
    generating: 'তৈরি হচ্ছে...',
  },
  mr: {
    ...commonKeys,
    title: 'क्रॉपजीपीटी',
    dashboard: 'डॅशबोर्ड',
    scanner: 'स्कॅनर',
    chatbot: 'चॅटबॉट',
    weather: 'हवामान',
    marketPrices: 'बाजारभाव',
    yieldProduction: 'उत्पादन',
    fetchWeather: 'तुमचे हवामान आणत आहे...',
    weatherError: 'हवामान आणता आले नाही. कृपया स्थान प्रवेशास अनुमती द्या.',
    selectState: 'राज्य निवडा',
    selectCity: 'शहर निवडा',
    selectCrop: 'पीक निवडा',
    fetch: 'आणा',
    startScan: 'कॅमेरा सुरू करा',
    capture: 'कॅप्चर आणि विश्लेषण करा',
    stopScan: 'कॅमेरा बंद करा',
    scanResult: 'स्कॅन परिणाम',
    askMe: 'शेतीबद्दल विचारा...',
    send: 'पाठवा',
    lightMode: 'लाइट मोड',
    darkMode: 'डार्क मोड',
    uploadImage: 'प्रतिमा अपलोड करा',
    search: 'शोधा',
    waterNeeds: 'पिकांची पाण्याची गरज',
    searchLocationPlaceholder: 'शहराचे नाव प्रविष्ट करा...',
    analyzing: 'विश्लेषण करत आहे...',
    uploadPrompt: 'पिकाचा एक स्पष्ट फोटो अपलोड करा',
    cameraOff: 'कॅमेरा बंद आहे',
    governmentSchemes: 'सरकारी योजना',
    retake: 'पुन्हा घ्या',
    uploadAnother: 'दुसरे अपलोड करा',
    fertilizers: 'खते',
    pesticides: 'कीटकनाशके',
    recommendations: 'शिफारसी',
    farmingCalendar: 'शेती कॅलेंडर',
    generateSchedule: 'वेळापत्रक तयार करा',
    generating: 'तयार होत आहे...',
  },
  te: {
    ...commonKeys,
    title: 'క్రాప్‌జిపిటి',
    dashboard: 'డాష్‌బోర్డ్',
    scanner: 'స్కానర్',
    chatbot: 'చాట్‌బాట్',
    weather: 'వాతావరణం',
    marketPrices: 'మార్కెట్ ధరలు',
    yieldProduction: 'దిగుబడి ఉత్పత్తి',
    fetchWeather: 'మీ వాతావరణం పొందబడుతోంది...',
    weatherError: 'వాతావరణం పొందడం సాధ్యం కాలేదు. దయచేసి స్థాన ప్రాప్యతను అనుమతించండి.',
    selectState: 'రాష్ట్రం ఎంచుకోండి',
    selectCity: 'నగరం ఎంచుకోండి',
    selectCrop: 'పంట ఎంచుకోండి',
    fetch: 'పొందండి',
    startScan: 'కెమెరా ప్రారంభించండి',
    capture: 'చిత్రం తీసి విశ్లేషించండి',
    stopScan: 'కెమెరా ఆపండి',
    scanResult: 'స్కాన్ ఫలితం',
    askMe: 'వ్యవసాయం గురించి నన్ను అడగండి...',
    send: 'పంపండి',
    lightMode: 'లైట్ మోడ్',
    darkMode: 'డార్క్ మోడ్',
    uploadImage: 'చిత్రాన్ని అప్‌లోడ్ చేయండి',
    search: 'వెతకండి',
    waterNeeds: 'పంట నీటి అవసరాలు',
    searchLocationPlaceholder: 'నగరం పేరు నమోదు చేయండి...',
    analyzing: 'విశ్లేషిస్తోంది...',
    uploadPrompt: 'పంట యొక్క స్పష్టమైన ఫోటోను అప్‌లోడ్ చేయండి',
    cameraOff: 'కెమెరా ఆఫ్ చేయబడింది',
    governmentSchemes: 'ప్రభుత్వ పథకాలు',
    retake: 'మళ్ళీ తీసుకోండి',
    uploadAnother: 'మరొకటి అప్‌లోడ్ చేయండి',
    fertilizers: 'ఎరువులు',
    pesticides: 'పురుగుమందులు',
    recommendations: 'సిఫార్సులు',
    farmingCalendar: 'వ్యవసాయ క్యాలెండర్',
    generateSchedule: 'షెడ్యూల్‌ను రూపొందించండి',
    generating: 'రూపొందించబడుతోంది...',
  },
};

export const indianStates: { [key: string]: string[] } = {
  'Andhra Pradesh': ['Visakhapatnam', 'Vijayawada', 'Guntur'],
  'Arunachal Pradesh': ['Itanagar', 'Tawang'],
  'Assam': ['Guwahati', 'Dibrugarh', 'Silchar'],
  'Bihar': ['Patna', 'Gaya', 'Muzaffarpur'],
  'Chhattisgarh': ['Raipur', 'Bhilai', 'Bilaspur'],
  'Goa': ['Panaji', 'Margao'],
  'Gujarat': ['Ahmedabad', 'Surat', 'Vadodara'],
  'Haryana': ['Faridabad', 'Gurugram', 'Panipat'],
  'Himachal Pradesh': ['Shimla', 'Manali'],
  'Jharkhand': ['Ranchi', 'Jamshedpur', 'Dhanbad'],
  'Karnataka': ['Bengaluru', 'Mysuru', 'Hubballi'],
  'Kerala': ['Thiruvananthapuram', 'Kochi', 'Kozhikode'],
  'Madhya Pradesh': ['Indore', 'Bhopal', 'Jabalpur'],
  'Maharashtra': ['Mumbai', 'Pune', 'Nagpur'],
  'Manipur': ['Imphal'],
  'Meghalaya': ['Shillong'],
  'Mizoram': ['Aizawl'],
  'Nagaland': ['Kohima', 'Dimapur'],
  'Odisha': ['Bhubaneswar', 'Cuttack', 'Rourkela'],
  'Punjab': ['Ludhiana', 'Amritsar', 'Jalandhar'],
  'Rajasthan': ['Jaipur', 'Jodhpur', 'Udaipur'],
  'Sikkim': ['Gangtok'],
  'Tamil Nadu': ['Chennai', 'Coimbatore', 'Madurai'],
  'Telangana': ['Hyderabad', 'Warangal', 'Nizamabad'],
  'Tripura': ['Agartala'],
  'Uttar Pradesh': ['Lucknow', 'Kanpur', 'Ghaziabad'],
  'Uttarakhand': ['Dehradun', 'Haridwar'],
  'West Bengal': ['Kolkata', 'Asansol', 'Siliguri'],
};

export const crops = ['Rice', 'Wheat', 'Maize', 'Cotton', 'Sugarcane', 'Soybean', 'Potato', 'Tomato', 'Onion'];